# Generated by Django 4.1.1 on 2022-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='roll',
        ),
        migrations.AddField(
            model_name='magazine',
            name='desc',
            field=models.TextField(default='Its time to read more about the Article'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='email',
            field=models.EmailField(default='abcd.....@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='magazine',
            name='img',
            field=models.ImageField(default='article.jpg', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title',
            field=models.CharField(default='Article', max_length=50),
        ),
    ]
