# Generated by Django 4.1.1 on 2022-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_remove_magazine_name_remove_magazine_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='img',
            field=models.ImageField(default='pics/article.jpg', upload_to='pics'),
        ),
    ]
